# development:
FROM node:lts-alpine as development

WORKDIR /usr/src/app

COPY ./package*.json ./yarn.lock ./

RUN yarn install

COPY . .

CMD yarn start:dev

# production:
FROM node:lts-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./package*.json ./yarn.lock ./

RUN yarn install --prod && yarn cache clean

COPY . .

RUN yarn build

CMD yarn start:prod
