version: '3.7'

services:
  postgresdb_service:
    container_name: postgresdb_service
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-dev-pass
      POSTGRES_DB: development_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nodeapi_service:
    build:
      context: ./../
      target: development
      dockerfile: ./.docker/node/dockerfile
    command: yarn start:dev
    depends_on:
      - postgresdb_service
    environment:
      NODE_ENV: docker_development
      PORT: 3000
      POSTGRES_HOST: postgresdb_service
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-dev-pass
      POSTGRES_DB: development_db
    volumes:
      - ./../src:/usr/src/app/src
    ports:
      - 3000:3000